USE DVDLibrary
GO

CREATE LOGIN  DvdLibraryApp WITH PASSWORD='testing123'
GO

CREATE USER DvdLibraryApp FOR LOGIN DvdLibraryApp
GO

GRANT EXECUTE ON DeleteDVD TO DvdLibraryAPP
GRANT EXECUTE ON GetAll TO DvdLibraryAPP
GRANT EXECUTE ON GetByDirector TO DvdLibraryAPP
GRANT EXECUTE ON GetByID TO DvdLibraryAPP
GRANT EXECUTE ON GetByRating TO DvdLibraryAPP
GRANT EXECUTE ON GetByTitle TO DvdLibraryAPP
GRANT EXECUTE ON GetByYear TO DvdLibraryAPP
GRANT EXECUTE ON NewDVD TO DvdLibraryAPP
GRANT EXECUTE ON UpdateDVD TO DvdLibraryAPP
GO

GRANT SELECT ON DVDsADO TO DvdLibraryApp
GRANT SELECT ON DVDsEF TO DvdLibraryApp
GRANT INSERT ON DVDsADO TO DvdLibraryApp
GRANT INSERT ON DVDsEF TO DvdLibraryApp
GRANT UPDATE ON DVDsADO TO DvdLibraryApp
GRANT UPDATE ON DVDsEF TO DvdLibraryApp
GRANT DELETE ON DVDsADO TO DvdLibraryApp
GRANT DELETE ON DVDsEF TO DvdLibraryApp
GO